/**
 * The contract between the passkey UI and the relying party (the backend).
 * Every binary field is a base64url string, so the shapes travel as JSON.
 */

export interface User {
	/** The WebAuthn user handle, base64url. */
	id: string;
	/** Generated by the backend at registration, e.g. "Traveller 7K3QX2". */
	name: string;
}

/** `PublicKeyCredential.toJSON()` of a registration, per WebAuthn Level 3. */
export interface RegistrationResponseJSON {
	id: string;
	rawId: string;
	type: string;
	authenticatorAttachment?: string | null;
	clientExtensionResults: AuthenticationExtensionsClientOutputs;
	response: {
		clientDataJSON: string;
		attestationObject: string;
		authenticatorData?: string;
		transports?: string[];
		publicKey?: string;
		publicKeyAlgorithm?: number;
	};
}

/** `PublicKeyCredential.toJSON()` of an assertion, per WebAuthn Level 3. */
export interface AuthenticationResponseJSON {
	id: string;
	rawId: string;
	type: string;
	authenticatorAttachment?: string | null;
	clientExtensionResults: AuthenticationExtensionsClientOutputs;
	response: {
		clientDataJSON: string;
		authenticatorData: string;
		signature: string;
		userHandle?: string | null;
	};
}

export interface RelyingParty {
	/** Used for Signal API calls, which must name the RP ID the passkeys belong to. */
	readonly rpId: string;
	/** Fresh options for every attempt, for a new account with a generated name. */
	registrationOptions(): Promise<PublicKeyCredentialCreationOptionsJSON>;
	/** Creates the account with its passkey and signs it in. */
	verifyRegistration(credential: RegistrationResponseJSON): Promise<User>;
	/** Fresh options for every attempt, with an empty `allowCredentials` so any discoverable passkey can answer. */
	authenticationOptions(): Promise<PublicKeyCredentialRequestOptionsJSON>;
	/** Verifies the assertion and signs its user in. */
	verifyAuthentication(credential: AuthenticationResponseJSON): Promise<User>;
	/** The signed-in user, or null. */
	currentUser(): Promise<User | null>;
	signOut(): Promise<void>;
}
