/**
 * Postgres storage (Neon) — docs/passkey-backend-requirements.md §8.
 *
 * The stores only see the small `Db` interface below, not the driver, so
 * the unit tests can run the same SQL on PGlite (Postgres compiled to
 * WebAssembly, in memory) instead of a database server.
 */
import { attachDatabasePool } from "@vercel/functions";
import pg from "pg";

export interface QueryResult<Row> {
	rows: Row[];
	/** Rows inserted, updated or deleted. */
	rowCount: number;
}

/** Runs one statement. Values go in `params` ($1, $2, …), never into the SQL text. */
export interface Sql {
	query<Row = Record<string, unknown>>(
		text: string,
		params?: unknown[],
	): Promise<QueryResult<Row>>;
}

export interface Db extends Sql {
	/**
	 * Runs `fn` on one connection inside BEGIN … COMMIT: all its statements
	 * take effect together, or none do if it throws. Inside, use only the
	 * `tx` it is given — a query on the Db itself would run outside the
	 * transaction.
	 */
	transaction<T>(fn: (tx: Sql) => Promise<T>): Promise<T>;
	close(): Promise<void>;
}

/**
 * Schema versions, applied in order and recorded in `schema_migrations`.
 * Never edit a migration that has run somewhere; append a new one instead.
 */
const MIGRATIONS: string[] = [
	`
	-- One row per account. The primary key is the WebAuthn user handle
	-- (base64url): random bytes the authenticator stores with the passkey and
	-- hands back at sign-in, so a passkey can be traced to its account.
	CREATE TABLE users (
		id text PRIMARY KEY,
		-- Generated by the server ("Traveller 7K3QX2"): sign-up asks for no name.
		-- It is what the passkey picker shows, and it need not be unique.
		name text NOT NULL,
		created_at timestamptz NOT NULL
	);

	-- One row per passkey.
	CREATE TABLE credentials (
		-- Credential ID chosen by the authenticator, base64url.
		id text PRIMARY KEY,
		user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
		-- COSE-encoded public key; the private key never leaves the authenticator.
		public_key bytea NOT NULL,
		-- COSE algorithm, e.g. -7 for ES256.
		algorithm integer NOT NULL,
		-- Signature counter, used to spot cloned authenticators. Synced passkeys
		-- stay at 0. Unsigned 32-bit, hence bigint.
		counter bigint NOT NULL,
		-- Such as {internal,hybrid}; tells the browser how to reach the authenticator.
		transports text[] NOT NULL,
		-- Authenticator model ID.
		aaguid text NOT NULL,
		-- Whether the passkey can be synced (BE flag) and currently is (BS flag).
		backup_eligible boolean NOT NULL,
		backed_up boolean NOT NULL,
		created_at timestamptz NOT NULL,
		last_used_at timestamptz
	);
	CREATE INDEX credentials_user_id ON credentials (user_id);

	-- One row per signed-in browser. Only the SHA-256 of the cookie token is kept,
	-- so a leaked database cannot be turned into working sessions.
	CREATE TABLE sessions (
		token_hash text PRIMARY KEY,
		user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
		created_at timestamptz NOT NULL,
		expires_at timestamptz NOT NULL,
		last_seen_at timestamptz NOT NULL,
		user_agent text
	);
	CREATE INDEX sessions_user_id ON sessions (user_id);
	CREATE INDEX sessions_expires_at ON sessions (expires_at);

	-- Challenges handed out by the options endpoints and not yet used.
	-- A row is deleted the moment a verify request presents it (single use).
	CREATE TABLE challenges (
		challenge text PRIMARY KEY,
		-- Issue order, to keep only the newest few per browser.
		seq bigint GENERATED ALWAYS AS IDENTITY,
		-- Random ID from the flow cookie: ties the challenge to one browser.
		flow_id text NOT NULL,
		type text NOT NULL CHECK (type IN ('registration', 'authentication')),
		-- The account a registration would create. It is not in users until
		-- verified, so merely asking for options creates nothing.
		user_id text,
		user_name text,
		created_at timestamptz NOT NULL,
		expires_at timestamptz NOT NULL
	);
	CREATE INDEX challenges_flow_id ON challenges (flow_id, seq);
	CREATE INDEX challenges_expires_at ON challenges (expires_at);

	-- Request counts per client address and endpoint group. In the database
	-- rather than in memory: on Vercel every request may reach a different
	-- instance of the function.
	CREATE TABLE rate_limits (
		key text PRIMARY KEY,
		count integer NOT NULL,
		reset_at timestamptz NOT NULL
	);
	CREATE INDEX rate_limits_reset_at ON rate_limits (reset_at);
	`,
];

/** Any constant: it names the lock that keeps two migrating servers apart. */
const MIGRATION_LOCK = 7_402_318_455;

/**
 * Brings the schema up to date, in one transaction: Postgres runs schema
 * changes transactionally, so a failed migration leaves nothing behind.
 * Several server instances may start at once (on Vercel, one per cold
 * start); the lock makes the others wait and then find nothing left to do.
 */
export const migrate = (db: Db): Promise<void> =>
	db.transaction(async (tx) => {
		await tx.query("SELECT pg_advisory_xact_lock($1)", [MIGRATION_LOCK]);
		await tx.query(`
			CREATE TABLE IF NOT EXISTS schema_migrations (
				version integer PRIMARY KEY,
				applied_at timestamptz NOT NULL DEFAULT now()
			)
		`);
		const { rows } = await tx.query<{ version: number | null }>(
			"SELECT max(version) AS version FROM schema_migrations",
		);
		const current = rows[0]?.version ?? 0;
		if (current > MIGRATIONS.length) {
			throw new Error(
				`The database schema (version ${current}) is newer than this code (version ${MIGRATIONS.length}).`,
			);
		}
		for (let version = current; version < MIGRATIONS.length; version++) {
			await tx.query(MIGRATIONS[version]);
			await tx.query("INSERT INTO schema_migrations (version) VALUES ($1)", [
				version + 1,
			]);
		}
	});

/**
 * Wraps a database so the migrations run just before its first query
 * rather than when the server starts. A request that needs no database —
 * reading the session of a visitor without a session cookie — then never
 * waits for the connection, nor wakes a suspended Neon database. If the
 * migrations fail, the next query tries them again.
 */
export const migrateOnFirstUse = (db: Db): Db => {
	let ready: Promise<void> | undefined;
	const whenReady = (): Promise<void> => {
		ready ??= migrate(db).catch((error: unknown) => {
			ready = undefined;
			throw error;
		});
		return ready;
	};
	return {
		async query<Row>(text: string, params?: unknown[]) {
			await whenReady();
			return db.query<Row>(text, params);
		},
		async transaction(fn) {
			await whenReady();
			return db.transaction(fn);
		},
		close: () => db.close(),
	};
};

/**
 * Neon's connection strings say `sslmode=require`, which node-postgres
 * already treats as `verify-full` (encrypted, and the server's certificate
 * checked) while printing a warning that this will change. Asking for
 * `verify-full` keeps today's behaviour and silences the warning; Neon's
 * certificates are publicly trusted, so the check passes.
 */
const withVerifiedTls = (connectionString: string): string => {
	const url = new URL(connectionString);
	const mode = url.searchParams.get("sslmode");
	if (mode === "prefer" || mode === "require" || mode === "verify-ca") {
		url.searchParams.set("sslmode", "verify-full");
	}
	return url.toString();
};

/** `bigint` columns come back as strings by default; every one here fits a JS number. */
const types = {
	getTypeParser: ((oid: number, format?: "text" | "binary") =>
		oid === pg.types.builtins.INT8
			? Number
			: pg.types.getTypeParser(oid, format)) as typeof pg.types.getTypeParser,
};

/**
 * Connects to Postgres through a connection pool. With Neon, use the pooled
 * connection string (host name ending in `-pooler`): it can serve many more
 * clients than a direct connection. Only transaction-scoped features work
 * through that pooler, which is why the migration lock is a transaction lock.
 */
export const connectDatabase = (connectionString: string): Db => {
	const pool = new pg.Pool({
		connectionString: withVerifiedTls(connectionString),
		types,
		// One request needs at most one connection at a time.
		max: 5,
		// Fail a request instead of hanging when the database is unreachable.
		connectionTimeoutMillis: 10_000,
		idleTimeoutMillis: 5_000,
	});
	// A connection that breaks while idle in the pool (say, the database
	// restarted) emits an error; unhandled, it would crash the process.
	pool.on("error", (error) => {
		console.warn("[passkey] idle database connection failed:", error.message);
	});
	// On Vercel, keeps the function alive until idle connections are closed,
	// so none leak when the instance is suspended. Does nothing elsewhere.
	attachDatabasePool(pool);

	const toResult = <Row>(result: pg.QueryResult): QueryResult<Row> => ({
		rows: result.rows as Row[],
		rowCount: result.rowCount ?? 0,
	});

	return {
		async query<Row>(text: string, params?: unknown[]) {
			return toResult<Row>(await pool.query(text, params));
		},

		async transaction(fn) {
			const client = await pool.connect();
			try {
				await client.query("BEGIN");
				const result = await fn({
					async query<Row>(text: string, params?: unknown[]) {
						return toResult<Row>(await client.query(text, params));
					},
				});
				await client.query("COMMIT");
				client.release();
				return result;
			} catch (error) {
				// If even the rollback fails the connection is broken: passing
				// the error to release() closes it instead of reusing it.
				const broken = await client.query("ROLLBACK").then(
					() => undefined,
					(rollbackError: Error) => rollbackError,
				);
				client.release(broken);
				throw error;
			}
		},

		close: () => pool.end(),
	};
};
